# Generated by Django 6.0.6 on 2026-06-13 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimiento',
            options={'ordering': ('estado', 'fecha_compromiso', '-prioridad', 'orden', 'titulo'), 'verbose_name': 'procedimiento', 'verbose_name_plural': 'procedimientos'},
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='completado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado')], default='pendiente', max_length=16),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='fecha_compromiso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=12),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procedimientos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='resultado',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Recordatorio',
        ),
    ]
