# Generated by Django 6.0.6 on 2026-06-15 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_procedimiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='tipo',
            field=models.CharField(choices=[('procedimiento', 'Procedimiento'), ('gestion', 'Gestion interna')], default='procedimiento', max_length=20),
        ),
    ]
