# Generated by Django 6.0.6 on 2026-06-15 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_procedimiento_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudSicret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_netcracker', models.CharField(max_length=80)),
                ('rbd', models.CharField(max_length=40)),
                ('zona', models.CharField(max_length=80)),
                ('comuna', models.CharField(max_length=120)),
                ('nombre_escuela', models.CharField(max_length=180)),
                ('direccion', models.CharField(max_length=240)),
                ('ip_servicio', models.CharField(max_length=80)),
                ('instancia', models.CharField(max_length=120)),
                ('nombre_contacto', models.CharField(max_length=160)),
                ('telefono', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=180)),
                ('estado_enlace', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online'), ('intermitente', 'Intermitente')], max_length=20)),
                ('descripcion_falla', models.CharField(choices=[('sin_servicio', 'Sin servicio'), ('lentitud', 'Lentitud'), ('intermitencia', 'Intermitencia'), ('no_navega', 'No navega'), ('equipo_apagado', 'Equipo apagado / sin energia'), ('otra', 'Otra falla')], max_length=40)),
                ('detalle_adicional', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_sicret', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud SICRET',
                'verbose_name_plural': 'solicitudes SICRET',
                'ordering': ('-creado_en',),
            },
        ),
    ]
