# Generated by Django 6.0.6 on 2026-06-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_solicitudsicret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudsicret',
            name='descripcion_falla',
            field=models.CharField(choices=[('enlace_offline', 'Enlace Offline'), ('enlace_intermitente', 'Enlace intermitente'), ('falla_ups', 'Falla de UPS'), ('falla_rack', 'Falla en Rack'), ('cliente_problemas_pruebas', 'Cliente con problemas para realizar pruebas'), ('cliente_exige_visita', 'Cliente exige visita tecnica'), ('switch_huawei_desconectado', 'Switch Huawei desconectado'), ('corte_fibra_optica', 'Corte de Fibra Optica')], max_length=40),
        ),
    ]
