# Generated by Django 6.0.6 on 2026-06-15 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_solicitudsicret_descripcion_falla'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudsicret',
            name='estado_sicret',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('enviado_terreno', 'Enviado a terreno'), ('en_pausa', 'En pausa'), ('cerrado', 'Cerrado')], default='en_proceso', max_length=24),
        ),
        migrations.AddField(
            model_name='solicitudsicret',
            name='estado_sicret_actualizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudsicret',
            name='estado_sicret_actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estados_sicret_actualizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
