# Generated by Django 6.0.6 on 2026-06-16 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_solicitudsicret_estado_sicret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimiento',
            name='archivo',
            field=models.FileField(blank=True, upload_to='procedimientos/'),
        ),
        migrations.AddField(
            model_name='solicitudsicret',
            name='comentario_encargado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitudsicret',
            name='ticket_sicret',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='EnlaceOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('descripcion', models.CharField(blank=True, max_length=240)),
                ('url', models.URLField(max_length=500)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enlaces_operativos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'enlace operativo',
                'verbose_name_plural': 'enlaces operativos',
                'ordering': ('categoria', 'titulo'),
            },
        ),
    ]
