# Generated by Django 6.0.6 on 2026-06-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seed_enlaces_operativos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='enlace',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
