# Generated by Django 6.0.6 on 2026-06-17 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_procedimiento_enlace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudSagec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_caida', models.DateField()),
                ('rbd', models.CharField(max_length=40)),
                ('motivo_ingreso', models.CharField(choices=[('falla_masiva', 'Falla Masiva'), ('responsabilidad_terceros', 'Responsabilidad Terceros')], max_length=40)),
                ('numero_ticket', models.CharField(max_length=80)),
                ('motivo_falla_terceros', models.CharField(choices=[('corte_fibra_accidental', 'Corte de fibra accidental'), ('corte_energia', 'Corte de energia electrica masivo o localizado'), ('desconexion_equipos', 'Desconexion de equipos'), ('robo_equipos', 'Robo de equipos'), ('catastrofe', 'Catastrofe: incendio, inundaciones, etc.')], max_length=60)),
                ('id_falla_asociada', models.CharField(blank=True, max_length=80)),
                ('ticket_sagec', models.CharField(blank=True, max_length=80)),
                ('comentario_encargado', models.TextField(blank=True)),
                ('estado_sagec', models.CharField(choices=[('preparacion', 'En preparacion'), ('ingresado', 'Ingresado a SAGEC'), ('revision', 'En revision'), ('cerrado', 'Cerrado')], default='preparacion', max_length=24)),
                ('estado_sagec_actualizado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_sagec', to=settings.AUTH_USER_MODEL)),
                ('estado_sagec_actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estados_sagec_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud SAGEC',
                'verbose_name_plural': 'solicitudes SAGEC',
                'ordering': ('-creado_en',),
            },
        ),
    ]
