# Generated by Django 6.0.6 on 2026-06-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RbdServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rbd', models.PositiveIntegerField(unique=True)),
                ('nombre_establecimiento', models.CharField(blank=True, max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('localidad', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('zona', models.CharField(blank=True, max_length=40)),
                ('zonal', models.CharField(blank=True, max_length=40)),
                ('tecnologia', models.CharField(blank=True, max_length=120)),
                ('tipo', models.CharField(blank=True, max_length=120)),
                ('status_imaster', models.CharField(blank=True, max_length=80)),
                ('fiscalizacion', models.CharField(blank=True, max_length=80)),
                ('vigencia', models.CharField(blank=True, max_length=80)),
                ('matricula', models.CharField(blank=True, max_length=40)),
                ('tipo_ont', models.CharField(blank=True, max_length=120)),
                ('puerta', models.CharField(blank=True, max_length=120)),
                ('nodo', models.CharField(blank=True, max_length=160)),
                ('bw_nacional', models.FloatField(blank=True, null=True)),
                ('bw_internacional', models.FloatField(blank=True, null=True)),
                ('bw', models.FloatField(blank=True, null=True)),
                ('fw_usg', models.CharField(blank=True, max_length=120)),
                ('serie_usg', models.CharField(blank=True, max_length=120)),
                ('codigo_servicio_ncc', models.CharField(blank=True, max_length=140)),
                ('vlan', models.CharField(blank=True, max_length=40)),
                ('codigo_servicio_oss', models.CharField(blank=True, max_length=140)),
                ('ip', models.CharField(blank=True, max_length=80)),
                ('dependencia_mpls', models.CharField(blank=True, max_length=180)),
                ('por', models.CharField(blank=True, max_length=120)),
                ('ont', models.CharField(blank=True, max_length=120)),
                ('tiene_rfs', models.CharField(blank=True, max_length=40)),
                ('rfs', models.CharField(blank=True, max_length=160)),
                ('caja', models.CharField(blank=True, max_length=120)),
                ('fil', models.CharField(blank=True, max_length=120)),
                ('servicio_existente_oss', models.CharField(blank=True, max_length=140)),
                ('tiene_ov', models.CharField(blank=True, max_length=40)),
                ('orden_venta', models.CharField(blank=True, max_length=120)),
                ('estado_ov', models.CharField(blank=True, max_length=120)),
                ('bpi', models.CharField(blank=True, max_length=200)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'servicio RBD',
                'verbose_name_plural': 'servicios RBD',
                'ordering': ('rbd',),
            },
        ),
    ]
