# Generated by Django 6.0.6 on 2026-06-07 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RbdContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(blank=True, max_length=180)),
                ('telefono', models.CharField(blank=True, max_length=80)),
                ('celular', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=180)),
                ('cargo', models.CharField(blank=True, max_length=140)),
                ('fuente', models.CharField(blank=True, max_length=120)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='rbd.rbdservicio')),
            ],
            options={
                'verbose_name': 'contacto RBD',
                'verbose_name_plural': 'contactos RBD',
                'ordering': ('servicio__rbd', 'orden'),
                'constraints': [models.UniqueConstraint(fields=('servicio', 'orden'), name='rbd_contacto_unico_por_orden')],
            },
        ),
    ]
