# Generated by Django 6.0.6 on 2026-06-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbd", "0002_rbdcontacto"),
    ]

    operations = [
        migrations.AddField(
            model_name="rbdservicio",
            name="jornada_categoria",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="rbdservicio",
            name="jornada_horario",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="rbdservicio",
            name="jornada_descripcion",
            field=models.CharField(blank=True, max_length=180),
        ),
    ]