# Generated by Codex on 2026-06-25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rbd", "0003_rbdservicio_jornada"),
    ]

    operations = [
        migrations.AddField(
            model_name="rbdservicio",
            name="dado_baja",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="rbdservicio",
            name="baja_fecha",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rbdservicio",
            name="baja_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rbd_servicios_dados_baja",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
