# Generated by Codex on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbd", "0004_rbdservicio_baja"),
    ]

    operations = [
        migrations.AddField(
            model_name="rbdservicio",
            name="baja_partner",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="rbdservicio",
            name="baja_observacion_mineduc",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="rbdservicio",
            name="baja_decreto",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="rbdservicio",
            name="baja_notificacion_fecha",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rbdservicio",
            name="baja_ov",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="rbdservicio",
            name="baja_observacion",
            field=models.TextField(blank=True),
        ),
    ]
