# Generated by Django 6.0.6 on 2026-06-26 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbd', '0005_rbdservicio_baja_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RbdHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('baja', 'Dado de baja'), ('eliminado', 'Eliminado')], db_index=True, max_length=20)),
                ('rbd', models.PositiveIntegerField(db_index=True)),
                ('nombre_establecimiento', models.CharField(blank=True, max_length=255)),
                ('bpi', models.CharField(blank=True, max_length=200)),
                ('codigo_servicio_oss', models.CharField(blank=True, max_length=140)),
                ('ip', models.CharField(blank=True, max_length=80)),
                ('tecnologia', models.CharField(blank=True, max_length=120)),
                ('zona', models.CharField(blank=True, max_length=40)),
                ('localidad', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('detalle', models.TextField(blank=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rbd_historial_acciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial RBD',
                'verbose_name_plural': 'historial RBD',
                'ordering': ('-creado_en', '-id'),
            },
        ),
    ]
