# Generated by Django 6.0.6 on 2026-06-04 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroBitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=80)),
                ('rbd', models.CharField(max_length=40)),
                ('vinculo_ticket', models.CharField(max_length=500)),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_bitacora', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de bitacora',
                'verbose_name_plural': 'registros de bitacora',
                'ordering': ('-dia', '-hora'),
                'constraints': [models.UniqueConstraint(fields=('dia', 'hora'), name='bitacora_unica_por_dia_hora')],
            },
        ),
    ]
