# Generated by Django 6.0.6 on 2026-06-04 03:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='registrobitacora',
            name='bitacora_unica_por_dia_hora',
            constraint=models.UniqueConstraint(fields=('dia', 'hora'), name='bitacora_unica_por_dia_hora', violation_error_message='Ya existe un agendamiento registrado para ese dia y hora.'),
        ),
    ]
