# Generated by Django 6.0.6 on 2026-06-10

from django.db import migrations, models


def marcar_agendas_fin_de_semana(apps, schema_editor):
    RegistroBitacora = apps.get_model("bitacora", "RegistroBitacora")
    ids_fin_de_semana = [
        registro.id
        for registro in RegistroBitacora.objects.only("id", "dia")
        if registro.dia and registro.dia.weekday() >= 5
    ]
    if ids_fin_de_semana:
        RegistroBitacora.objects.filter(id__in=ids_fin_de_semana).update(es_fin_de_semana=True)


class Migration(migrations.Migration):

    dependencies = [
        ("bitacora", "0002_alter_registrobitacora_bitacora_unica_por_dia_hora"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrobitacora",
            name="es_fin_de_semana",
            field=models.BooleanField(default=False, verbose_name="agendamiento de fin de semana"),
        ),
        migrations.RunPython(marcar_agendas_fin_de_semana, migrations.RunPython.noop),
    ]