# Generated by Django 6.0.6 on 2026-06-12 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0003_registrobitacora_es_fin_de_semana'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registrobitacora',
            name='bitacora_unica_por_dia_hora',
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='cancelado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_bitacora_cancelados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='estado',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('cancelada', 'Cancelada')], default='agendada', max_length=20),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddConstraint(
            model_name='registrobitacora',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'agendada')), fields=('dia', 'hora'), name='bitacora_unica_por_dia_hora', violation_error_message='Ya existe un agendamiento registrado para ese dia y hora.'),
        ),
    ]
