# Generated by Django 6.0.6 on 2026-06-15 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacora', '0004_remove_registrobitacora_bitacora_unica_por_dia_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrobitacora',
            name='llamada_actualizada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrobitacora',
            name='llamada_realizada',
            field=models.BooleanField(default=False),
        ),
    ]
